#45 initial slack action
telia-actions/look-up-slack-user pull request #1
Opened 2021-11-05 09:39 UTC by AivarasGluodas

2021-11-05 11:07 UTC, ech018 requested changes

2021-11-05 11:28 UTC, raihle requested changes

2021-11-05 11:28 UTC, raihle commented on src/__tests__/runner.test.ts
> +  it('should parse inputs and set outputs', async () => {
You are expecting on a lot of different variables, and almost any function will "parse inputs and set outputs" in some way. Maybe break the test case up into `gets email from github inputs`, `gets slack token from github inputs`, `sets username in github output`, `doesn't invoke the failure callback`, etc.

2021-11-05 11:28 UTC, raihle commented on src/__tests__/runner.test.ts
> +    expect(getInputSpy).toHaveBeenCalledTimes(2);
No need to expect on these spies again as they are covered by earlier tests.

2021-11-05 11:28 UTC, raihle commented on src/__tests__/runner.test.ts
> +  it('should parse inputs and set outputs', async () => {
However, I don't think you necessarily need to check the interactions with every spy in such detail. I think it is enough to do something like:

* Set up getInput to return mocked values for email and token (done)
* Set up lookUpUserByEmail to return a mocked value, but only if it is passed the mocked email (and token?)
* Check that setOutput was called with the expected value (done)
* Check that setFailed was not called (done)

2021-11-05 11:28 UTC, raihle commented on src/utils/slackClient/slackClient.ts
> +let slackClient: WebClient;
I think this was better before. As a user of the slackClient, now I have to call `initializeClient` before `lookUpUserByEmail`, but have no way of knowing that.

Either:
* Make the client a parameter of `lookUpUserByEmail` so that the dependency is explicit (and easy to test)
* Make the token a parameter of `lookUpUserByEmail`, which then creates its own client (could cache it if necessary, but I doubt that) so that the dependency is "removed" (but hard to test)
* Make our own client which wraps the Slack client and has `lookUpUserByEmail` as a method (also hard to test)

2021-11-05 11:28 UTC, raihle commented on src/utils/slackClient/types.ts
> +export type InitializeClientOptions = {
Why not export these types from slackClient.ts? They are closely related.

2021-11-05 12:03 UTC, AivarasGluodas commented on src/runner.ts
> +    if (lookUpResponse.ok) {
I think we talked about this. If user can't be resolved we don't fail the build - we skip notifying user and only notify slack channel. Is that ok?

2021-11-05 12:05 UTC, AivarasGluodas commented on .eslintrc.json
> +    "eslint-comments/no-use": "off",
Not sure. I think we could adress this when we are working on template project? Currently this is just copied over from other actions :(

2021-11-05 12:08 UTC, AivarasGluodas commented on src/utils/slackClient/types.ts
> +export type InitializeClientOptions = {
i thought it was cleaner to have separate file for types but we can do this aswell

2021-11-05 12:10 UTC, AivarasGluodas commented on src/__tests__/runner.test.ts
> +  it('should parse inputs and set outputs', async () => {
i'm open to suggestions for happy path test case name :D

2021-11-05 12:16 UTC, ech018 commented on src/runner.ts
> +    if (lookUpResponse.ok) {
You are right. But maybe we would like to have debug message, that user was not found.

2021-11-05 12:22 UTC, AivarasGluodas commented on src/utils/slackClient/types.ts
> +export type InitializeClientOptions = {
also they both are in slackClient folder, which also indicates that they are closely related

2021-11-05 12:23 UTC, AivarasGluodas commented on src/utils/slackClient/slackClient.ts
> +let slackClient: WebClient;
i don't fully understand 3rd option can you explain it a bit more?

2021-11-05 12:31 UTC, AivarasGluodas commented on src/runner.ts
> +    if (lookUpResponse.ok) {
ok

2021-11-08 11:18 UTC, raihle commented on src/utils/slackClient/slackClient.ts
> +let slackClient: WebClient;
3rd option would be the object oriented approach. A `SlackClient` class that creates (or accepts in constructor) a slack `WebClient` and exposes a `lookUpByEmail` method.

2021-11-08 11:22 UTC, raihle commented on src/__tests__/runner.test.ts
> +  it('should parse inputs and set outputs', async () => {
"uses email and slack access token given by workflow to look up and return a slack user ID"

2021-11-08 11:23 UTC, raihle commented on src/utils/slackClient/slackClient.ts
> +let slackClient: WebClient;
(the benefit would be that it's obvious to the user that the class must be instantiated before the method can be called)

2021-11-08 13:56 UTC, ech018 approved these changes

2021-11-08 14:20 UTC, raihle commented on src/utils/slackClient/slackClient.ts
> +let slackClient: WebClient;
To stay similar with existing code but still fix the unexpected invisible dependency, just make the client a parameter to `lookUpUserByEmail` instead of a module-level variable in slackClient.ts (option 1).

2021-11-09 11:38 UTC, raihle approved these changes

2021-11-09 11:38 UTC, raihle commented on src/__tests__/github-action.test.ts
> +    expect(getInputSpy).toHaveBeenCalledTimes(2);
They don't hurt right now, but I think these expects (on getInputSpy, createAppContainerSpy, and lookUpUserByEmailMock) are unnecessary. Based on how getInputSpy and lookUpUserByEmailMock are set up, they will only return the expected result if they are called with the expected input - so no need to check that twice.

2021-11-09 11:38 UTC, raihle commented on src/app.ts
> +export const createAppContainer = (config: CreateAppConfig) => {
Is this a single object to contain every dependency, that will be injected everywhere? I am fine with that, given:
* It is immutable once created. Perhaps we should even `Object.freeze` it or something, but that can be discussed later
* Injection points (i.e. slack-client.ts) are typed to specify exactly the dependencies they need, not a generic "all injectable dependencies" type (this PR looks good in that regard)
* The project doesn't grow too much (unlikely in this case), since we are effectively dealing with a global namespace and a lack of isolation

2021-11-09 11:38 UTC, raihle commented on src/app.ts
> +    agent: createProxyAgent(),
It shouldn't be a problem right now, but it's a bit weird that we just assume that there must be a proxy and throw (in createProxyAgent) otherwise.

2021-11-09 11:40 UTC, merged